"""Remove embedding column and enforce vector constraints

Revision ID: 2b7e1ba9dfa5
Revises: 3f8a8c554cc7
Create Date: 2025-03-29 17:40:26.959541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '2b7e1ba9dfa5'
down_revision: Union[str, None] = '3f8a8c554cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memory', 'prompt_embedding',
               existing_type=Vector(dim=1536),
               nullable=True)
    op.alter_column('memory', 'response_embedding',
               existing_type=Vector(dim=1536),
               nullable=True)
    op.drop_column('memory', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory', sa.Column('embedding', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.alter_column('memory', 'response_embedding',
               existing_type=Vector(dim=1536),
               nullable=True)
    op.alter_column('memory', 'prompt_embedding',
               existing_type=Vector(dim=1536),
               nullable=True)
    # ### end Alembic commands ###
