"""add prompt and response embeddings with pgvector

Revision ID: 84009caec079
Revises: 2ce4d7b2bd4c
Create Date: 2025-03-24 16:53:17.191484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '84009caec079'
down_revision: Union[str, None] = '2ce4d7b2bd4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory', sa.Column('prompt_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('memory', sa.Column('response_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory', 'response_embedding')
    op.drop_column('memory', 'prompt_embedding')
    # ### end Alembic commands ###
